[project]
name = "sup-convert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pillow>=12.1.0",
    "pymkv2>=2.1.2",
    "pysrt>=1.1.2",
    "pytesseract>=0.3.13",
]
